name: 'Custom C# Action'
description: 'GitHub Action plugin menggunakan C#'
author: 'Your Name'
inputs:
  mode:
    description: 'Mode should be deploy or test'
    required: true
    type: string
  frontend-path:
    description: 'Path to frontend'
    required: false
    type: string
  backend-path:
    description: 'Path to backend'
    required: false
    type: string
  test-path:
    description: 'Path to test'
    required: false
    type: string
  backend-appsettings-transform:
    description: 'Transform appsettings.json backend'
    required: false
    type: string
  test-appsettings-transform:
    description: 'Transform appsettings.json test'
    required: false
    type: string
  env-transform:
    description: 'Transform environment variables frontend'
    required: false
    type: string

outputs:
  result:
    description: 'Output from action'

runs:
  using: 'composite'
  steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore ${{ github.action_path }}/my-test-plugins.csproj
      shell: bash
    
    - name: Build and Run
      run: |
        TEST-PATH=$(echo "${{ inputs.test-path }}" | tr '\n' ' ')

        dotnet run --project ${{ github.action_path }}/my-test-plugins.csproj \
          --mode=${{ inputs.mode }} \
          --frontend-path=${{ inputs.frontend-path }} \
          --backend-path=${{ inputs.backend-path }} \
          --test-path="$TEST-PATH" \
          --backend-appsettings-transform=${{ inputs.backend-appsettings-transform }} \
          --test-appsettings-transform=${{ inputs.test-appsettings-transform }} \
          --env-transform=${{ inputs.env-transform }} \
      shell: bash